spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/expconv
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update


security:
  jwt:
    secret: cWZpcWlmdXFpb2Zxb2lmdXFvaWZ1cW9pZnVvcWlmdW9xaXVmb2lx
    access: 900000
    refresh: 2592000000
server:
  port: 5000

front:
  url: http://localhost:8080

